Sesion8/AerolineaDjango/AerolineaDjango/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('aplicaciones.empleados.urls'))
]

Sesion8/AerolineaDjango/aplicaciones/empleados/urls.py
from django.urls import path
from . import views

app_name = 'empleados_app'

urlpatterns = [
    path('empleados/index/', views.index, name='index-empleado'),
    path(
        'empleados/lista-empleados/',
        views.ListaEmpleados.as_view(),
        name='lista-empleados'),
    path(
        'empleados/crear-empleado',
        views.CrearEmpleado.as_view(),
        name='crear-empleado'),
    path(
        'empleados/modificar-empleado/<pk>/', # /<pk>/ ayuda a especificar la llave primaria de personaje esecífico que queremos
        views.ModificarEmpleado.as_view(),
        name='modificar-empleado'),
    path(
        'empleados/eliminar-empleado/<pk>/',
        views.EliminarEmpleado.as_view(),
        name='eliminar-empleado'),

    # urls API
    path(
        'api/empleados/lista',
        views.ListaAPIEmpleado.as_view(),
        name='lista-api-empleado'),
    path(
        'api/empleados/crear',
        views.CrearAPIEmpleado.as_view(),
        name='crear-api-empleado'),
    path(
        'api/empleados/obtener/<pk>/',
        views.ModificarAPIEmpleado.as_view(),
        name='obtener-api-empleado'),
    path(
        'api/empleados/modificar/<pk>/',
        views.ModificarAPIEmpleado.as_view(),
        name='modificar-api-empleado'),
    path(
        'api/empleados/modificar2/<pk>/',
        views.Modificar2APIEmpleado.as_view(),
        name='modificar2-api-empleado'),
    path(
        'api/empleados/eliminar/<pk>/',
        views.EliminarAPIEmpleado.as_view(),
        name='eliminar-api-empleado')
] 

Sesion8/AerolineaDjango/aplicaciones/empleados/models.py
from django.db import models

# Create your models here.
class Proyecto(models.Model):
    nombre_proyecto = models.CharField('Nombre proyecto', max_length=50)
    fecha_inicio = models.DateField('Fecha de inicio', auto_now=False, auto_now_add=False)
    fecha_fin = models.DateField('Fecha de fin', auto_now=False, auto_now_add=False)
    def __str__(self):
        return self.nombre_proyecto
class Cargo(models.Model):
    idcargo = models.IntegerField(primary_key=True) # definicion de llave primaria
    cargo = models.CharField('Cargo', max_length=60)

    def __str__(self):
        return self.cargo

class Empleado(models.Model):
    nombre = models.CharField('Nombre', max_length=60)
    telefono = models.CharField('Teléfono', max_length=60)
    correo = models.CharField('Correo', max_length=100)
    sueldo = models.DecimalField('Sueldo', max_digits=9, decimal_places=2)
    cargo = models.ForeignKey(Cargo, on_delete=models.CASCADE) 
    proyecto = models.ManyToManyField(Proyecto, blank=False, related_name='proyecto_empleado')

Sesion8/AerolineaDjango/aplicaciones/inicio/models.py
from django.db import models

# Create your models here.

Sesion8/AerolineaDjango/aplicaciones/login/models.py
from django.db import models

# Create your models here.

Sesion8/AerolineaDjango/aplicaciones/empleados/views.py
from django.shortcuts import render
from .models import Empleado, Cargo
from django.views.generic import (ListView,CreateView,UpdateView,DeleteView)
from django.urls import reverse_lazy
from rest_framework.generics import (ListAPIView, CreateAPIView, RetrieveAPIView, DestroyAPIView, UpdateAPIView, RetrieveUpdateAPIView)
from .serializer import EmpleadoSerializer, EmpleadoAllSerializer

# API Viesws
class ListaAPIEmpleado(ListAPIView):
    serializer_class = EmpleadoAllSerializer
    queryset = Empleado.objects.all()
class CrearAPIEmpleado(CreateAPIView):
    serializer_class = EmpleadoSerializer
class EliminarAPIEmpleado(DestroyAPIView):
    serializer_class = EmpleadoSerializer
    queryset = Empleado.objects.all()
class ObtenerAPIEmpleado(RetrieveAPIView):
    serializer_class = EmpleadoSerializer
    queryset = Empleado.objects.all()
class ModificarAPIEmpleado(RetrieveUpdateAPIView):
    serializer_class = EmpleadoSerializer
    queryset = Empleado.objects.all()
class Modificar2APIEmpleado(UpdateAPIView):
    serializer_class = EmpleadoSerializer
    queryset = Empleado.objects.all()

# Create your views here.
def index(request):
    return render(request, 'empleados/index.html') 

# views empleados
class ListaEmpleados(ListView):
    template_name = 'empleados/lista-empleados.html'
    model = Empleado
    context_object_name = 'lista_empleados'
class CrearEmpleado(CreateView):
    template_name = 'empleados/crear-empleado.html'
    model = Empleado
    fields = ['nombre', 'telefono','correo','sueldo','cargo']
    success_url = reverse_lazy('empleados_app:lista-empleados')
class ModificarEmpleado(UpdateView):
    template_name = 'empleados/modificar-empleado.html'
    model = Empleado
    fields = ['nombre', 'telefono','correo','sueldo','cargo']
    success_url = reverse_lazy('empleados_app:lista-empleados')
class EliminarEmpleado(DeleteView):
    template_name = 'empleados/eliminar-empleado.html'
    model = Empleado 
    success_url = reverse_lazy('empleados_app:lista-empleados') 

Sesion8/AerolineaDjango/aplicaciones/inicio/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'inicio/index.html') 

Sesion8/AerolineaDjango/aplicaciones/login/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render (request,'login/index.html') 
    

Sesion8/AerolineaDjango/templates/empleados/crear-empleado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear Empleado</title>
</head>
<body>
    <h2>Crear empleado</h2>
    <form action="" method="post">
        <table>
            {% csrf_token %}
            {{ form.as_table }}
        </table>
        <input type="submit" value="Guardar">
    </form>
</body>
</html>

Sesion8/AerolineaDjango/templates/empleados/eliminar-empleado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eliminar empleado</title>
</head>
<body>
    <h2>Eliminar Empleado</h2>
    <form action="" method="post">
        {% csrf_token %}
        Desea eliminar el empleado selecionado?
        <input type="submit" value="Sí">
        <a href="{% url 'empleados_app:lista-empleados' %}">Cancelar</a>
    </form>
</body>
</html>

Sesion8/AerolineaDjango/templates/empleados/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <h1>Primer Plantilla en Django</h1>
    
</body>
</html>

Sesion8/AerolineaDjango/templates/empleados/lista-empleados.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista Empleados</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <h2>Lista de empleados</h2>
        <a href="{% url 'empleados_app:crear-empleado' %} " class="btn btn-secundary">Nuevo empleado</a><br><br>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Sueldo</th>
                    <th>Cargo</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for e in lista_empleados %} 
                    <tr>
                        <td>{{e.id}}</td><td>{{e.nombre}}</td><td>{{e.sueldo}}</td><td>{{e.cargo.cargo}}</td>
                        <td><a href="{% url 'empleados_app:modificar-empleado' e.id %}">Modificar</a>
                        | <a href="{% url 'empleados_app:eliminar-empleado' e.id %}">Eliminar</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>

Sesion8/AerolineaDjango/templates/empleados/modificar-empleado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modificar Empleado</title>
</head>
<body>
    <h2>Modificar empleado</h2>
    <form action="" method="post">
        <table>
            {% csrf_token %}
            {{ form.as_table }}
        </table>
        <input type="submit" value="Actualizar">
    </form>
</body>
</html>

Sesion8/AerolineaDjango/templates/inicio/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=
    , initial-scale=1.0">
    <title>Inicio</title>
</head>
<body>
    <h1>Inicio</h1>
    <h2>Plantilla con Django</h2>
</body>
</html>

Sesion8/AerolineaDjango/templates/login/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <h1>Login</h1>
    <h2>Plantilla con Django/h2>
</body>
</html>